app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('images/favicon.ico')))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from .views import (
    HomePageView,
    AboutView,
    ProjectListView,
    SocialMediaView,
    ContactView,
)


app_name = 'core'


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('projects/', ProjectListView.as_view(), name='projects'),
    path('social-media/', SocialMediaView.as_view(), name='social'),
    path('contact/', ContactView.as_view(), name='contact'),
]

core/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.shortcuts import reverse
from cloudinary.models import CloudinaryField
import cloudinary.uploader


class About(models.Model):
    id = models.IntegerField(primary_key=True)
    slug = models.SlugField()
    text = models.TextField()


class Project(models.Model):
    id = models.IntegerField(primary_key=True)
    slug = models.SlugField()
    title = models.CharField(max_length=100)
    url = models.URLField(max_length=200)
    github = models.URLField(max_length=200)
    description = models.TextField()
    techs = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    image = CloudinaryField('image')

    """ Informative name for model """
    def __unicode__(self):
        try:
            public_id = self.image.public_id
        except AttributeError:
            public_id = ''
        return "Photo <%s:%s>" % (self.title, public_id)

    def __str__(self):
        return f"{self.id}: {self.title}"

    def get_absolute_url(self):
        return reverse("core:project-detail", kwargs={
            'slug': self.slug
        })
    
    class Meta:
        ordering = ['-id']

core/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=50,
        widget=forms.TextInput(attrs={
            "class": "form-control shadow-sm border-0",
            "placeholder": "Name"
        })
    )
    email = forms.EmailField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control shadow-sm border-0",
            "placeholder": "Email"
        })
    )
    phone = forms.CharField(
        max_length=13,
        widget=forms.TextInput(attrs={
            "class": "form-control shadow-sm border-0",
            "placeholder": "Phone"
        })
    )
    subject = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control shadow-sm border-0",
            "placeholder": "Subject"
        })
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={
            "class": "form-control shadow-sm border-0",
            "placeholder": "Message"
        })
    )

core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from django.conf import settings
from django.views.generic import View, ListView, DetailView, TemplateView
from .models import Project
from .forms import ContactForm
from random import choice


class HomePageView(View):
    def get(self, *args, **kwargs):
        projects = Project.objects.all()
        random_project1 = choice(Project.objects.all())
        context = {
            'projects': projects,
            "random_project1": random_project1,
        }
        return render(self.request, 'home.html', context, status=200)


class AboutView(View):
    def get(self, *args, **kwargs):
        context = {}
        return render(self.request, 'about.html', context, status=200)


class ProjectListView(ListView):
    model = Project
    paginate_by = 9
    template_name = 'projects.html'


class SocialMediaView(View):
    def get(self, *args, **kwargs):
        context = {}
        return render(self.request, 'social-media.html', context, status=200)


class ContactView(View):
    def get(self, *args, **kwargs):
        form = ContactForm()
        context = {
            'form': form
        }
        return render(self.request, 'contact.html', context, status=200)

    def post(self, *args, **kwargs):
        form = ContactForm(self.request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            subject = form.cleaned_data['subject']
            message = f"{name} ({email}, {phone}) says: {form.cleaned_data['message']}"
            try:
                send_mail(subject, message, email, ['jsharris.portfolio@gmail.com'])
                messages.success(self.request, "Your message has been sent")
                return redirect("core:contact")
            except BadHeaderError:
                messages.error(self.request, "Invalid header found. Try again.")
                return redirect("core:contact")
            except Exception as e:
                messages.error(self.request, "Something went wrong. Please try again.")
                return redirect("core:contact")

templates/about.html
{% extends "base.html" %}
{% load static %}
{% load cloudinary %}
{%  block content %}
{% include "components/navbar.html" with active="/about"  %}


<!-- Landing Section -->
<div class="site-section shadow-lg bg-light animate__animated animate__fadeIn text-center align-items-center justify-content-center" id="landing-section">
	<div class="container p-0">
		<div class="row mt-5 text-center align-items-center justify-content-center">
			<div class="col-10 m-0 p-0 m-3">
				<div class="jumbotron shadow bg-custom animate__animated animate__backInDown" id="landing-jumbo">
                    <h1>About</h1>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Landing Section -->

<!-- About Section -->
<div class="site-section bg-light animate__animated animate__fadeIn" id="site-section">
	<div class="container p-0">
		<div class="row mt-3 text-center align-items-center justify-content-center">
			<div class="col-md-8 m-0 p-0 animate__animated animate__backInUp">
				<h1 class="animate__animated animate__backInRight">Full-Stack Web Design and Development</h1>
				<!-- Jumbotron -->
				<div class="card bg-light shadow border-0 mt-3 text-center align-items-center justify-content-center animate__animated" id="landing-project-jumbo">
					<div class="text-dark text-center py-4 px-4">
	  					<div class="">
							<!-- Content -->
							<section>
                                <h3 class="font-weight-bold text-center dark-grey-text pb-2 animate__animated animate__bounceInRight">Curating the Online Presence of Artists, Innovators, Brands, and Businesses.</h3>
								<hr class="w-header my-4 animate__animated animate__bounceInLeft">
								<p class="lead text-center text-muted pt-2 mb-5 animate__animated animate__bounceInLeft">I can help with any aspect of the development process.</p>
								<div class="row">
									<!-- Panel -->
									<div class="col-md-6 mb-4 animate__animated animate__backInLeft">
										<!-- Card -->
										<div class="card text-center shadow-sm border-0">
											<div class="card-body">
												<span class="mt-4 pt-2"></p><i class="fas fa-laptop-code fa-3x"></i></span>
												<h5 class="font-weight-normal my-4 py-2">Design</h5>
												<p class="text-muted mb-4">I develop simple, stylish apps with straightforward content structure and thoughtful interactions.</p>
												<hr>
												<p>UX, UI, Web, Mobile, Apps, Logos</p>
											</div>
										</div>
										<!-- Card -->
									</div>
									<!-- Panel -->
									<!-- Panel -->
									<div class="col-md-6 mb-4 animate__animated animate__backInRight">
										<!-- Card -->
										<div class="card text-center shadow-sm border-0">
											<div class="card-body">
												<span class="mt-4 pt-2"></p><i class="fas fa-stream fa-3x"></i></span>
												<h5 class="font-weight-normal my-4 py-2">Front-End Development</h5>
												<p class="text-muted mb-4">I code user interfaces from scratch and bring life to creative ideas right in your browser.</p>
												<hr>
												<p>HTML, CSS, Sass, Bootstrap, React</p>
											</div>
										</div>
										<!-- Card -->
									</div>
									<!-- Panel -->
									<!-- Panel -->
									<div class="col-md mb-4 animate__animated animate__backInUp">
										<!-- Card -->
										<div class="card text-center shadow-sm border-0">
											<div class="card-body">
												<span class="mt-4 pt-2"></p><i class="fas fa-sitemap fa-3x"></i></span>
												<h5 class="font-weight-normal my-4 py-2">Back-End Development</h5>
												<p class="text-muted mb-4">I create safe and secure server-side logic to smoothly integrate data with the UI.</p>
												<hr>
												<p>Django, Flask, NodeJS, PostgreSQL, MongoDB, REST APIs</p>
											</div>
										</div>
										<!-- Card -->
									</div>
									<!-- Panel -->
								</div>
							</section>
							<!-- Content -->
						</div>
					</div>
  				</div>
  				<!-- Jumbotron -->
			</div>
		</div>
	</div>
</div>
<!-- About Section -->

<!-- Stack Overflow -->

<div class="site-section bg-white animate__animated animate__fadeIn" id="site-section">
    <div class="container p-0">
		<div class="row mt-3 text-center align-items-center justify-content-center">
			<div class="col-8 m-0 p-0 animate__animated animate__backInUp">
				<h1 class="animate__animated animate__backInRight">Professional Story</h1>
				<!-- Jumbotron -->
				<div class="card bg-light shadow border-0 mt-3 text-center align-items-center justify-content-center animate__animated" id="landing-project-jumbo">
					<div class="text-dark text-center py-5 px-4">
						<!-- Content -->
						<h5 class="text-muted mb-3 pb-2">Read my Developer Story on Stack Overflow or check out my connections on LinkedIn</h5>
                        <div class="card-deck">
                            <a href="https://stackoverflow.com/story/joshharris" class="nav-item bg-white text-secondary card shadow-sm border-0 bg-light animate__animated animate__backInLeft" target="_blank">
                                <div class="card-body">
                                    <h5 class="card-title"><i class="fab fa-stack-overflow fa-3x"></i></h5>
                                    <h4>Stack Overflow</h4>
                                </div>
                            </a>
                            <a href="https://www.linkedin.com/in/joshsharris/" class="nav-item bg-white text-secondary card shadow-sm border-0 bg-light animate__animated animate__backInRight" target="_blank">
                                <div class="card-body">
                                    <h5 class="card-title"><i class="fab fa-linkedin fa-3x"></i></h5>
                                    <h4>LinkedIn</h4>
                                </div>
                            </a>
                        </div>
                        <!-- Content -->

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Stack Overflow -->

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>J. Harris Web Dev</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/arrow.css' %}" />

    <link href="https://fonts.googleapis.com/css2?family=News+Cycle:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <!-- Facebook -->
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v7.0" nonce="zy7UeHk4"></script>
    <!-- Facebook -->

    <!-- Content -->
    {% block content  %}

    {% endblock content %}
    {% include 'components/footer.html' %}
    <!-- Content -->
        
    <!-- Scripts -->
    <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/499416/TweenLite.min.js"></script>
    <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/499416/EasePack.min.js"></script>
    <script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/499416/demo.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://kit.fontawesome.com/ec0fbf1158.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/index.js' %}"></script>
    {% block extra_scripts %}
    {% endblock extra_scripts %}
    {% block sm_scripts %}
    {% endblock sm_scripts %}
</body>
</html>

templates/components/footer.html
{% load static %}
<!-- Footer -->
<footer class="footer bg-light text-small shadow">

    <!-- Footer Elements -->
    <div class="container fixed">
  
      <div class="row">
        <div class="col-md p-3 text-center align-items-center justify-content-center">
            <a class="text-secondary nav-link" href="{% url 'core:home' %}">
                <h5 class="mb-0"><i class="far fa-copyright"></i> 2020 J. Harris Web Development</h5>
            </a>
        </div>
        <div class="col-md d-flex button-group text-center align-items-center justify-content-center">
            <a class="text-secondary nav-link foot-link" href="https://www.facebook.com/jharriswebdev/" class="mr-3" role="button"><i class="fab fa-facebook-f"></i></a>
            <a class="text-secondary nav-link foot-link" href="https://www.linkedin.com/in/joshsharris/" class="mr-3" role="button"><i class="fab fa-linkedin-in"></i></a>
            <a class="text-secondary nav-link foot-link" href="https://github.com/jharris711" class="mr-3" role="button"><i class="fab fa-github-alt"></i></a>
            <a class="text-secondary nav-link foot-link" href="https://twitter.com/jheeeeezy" class="mr-3" role="button"><i class="fab fa-twitter"></i></a>
            <a class="text-secondary nav-link foot-link" href="https://stackoverflow.com/story/joshharris" class="mr-3" role="button"><i class="fab fa-stack-overflow"></i></a>
            <a class="text-secondary nav-link foot-link" href="https://www.youtube.com/channel/UCUQ-fkPVp3grr4nGWlH8ppw" class="mr-1" role="button"><i class="fab fa-youtube"></i></a>
        </div>
      </div>
  
    </div>
    <!-- Footer Elements -->
  
  </footer>
  <!-- Footer -->

templates/components/navbar.html
{% load static %}
<div class="container">
  <nav class="navbar navbar-expand-lg shadow-sm fixed-top navbar-light bg-custom animate__animated animate__fadeIn">
    <div class="container">
      <a class="navbar-brand" href="{% url 'core:home' %}">
        <img src="{% static 'images/jhwd2.png' %}" width="35" height="30" class="d-inline-block align-top pr-2" alt="" loading="lazy">
      J. Harris Web Development
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mr-5">
          <li class="nav-item {% if active == '/' %}active{% endif %}">
            <a class="nav-link" href="{% url 'core:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item {% if active == '/about' %}active{% endif %}">
            <a class="nav-link" href="{% url 'core:about' %}">About</a>
          </li>
          <li class="nav-item {% if active == '/projects' %}active{% endif %}">
            <a class="nav-link" href="{% url 'core:projects' %}">Projects</a>
          </li>
          <li class="nav-item {% if active == '/social' %}active{% endif %}">
            <a class="nav-link" href="{% url 'core:social' %}">Social Media</a>
          </li>
          <li class="nav-item {% if active == '/contact' %}active{% endif %}">
            <a class="nav-link" href="{% url 'core:contact' %}">Contact</a>
          </li>
      </div>
    </div>
  </nav>  
</div>  

templates/contact.html
{% extends "base.html" %}
{% load static %}
{% load cloudinary %}
{%  block content %}
{% include "components/navbar.html" with active="/contact"  %}


<!-- Landing Section -->
<div class="site-section shadow-lg bg-light animate__animated animate__fadeIn text-center align-items-center justify-content-center" id="landing-section">
	<div class="container p-0">
		<div class="row mt-5 text-center align-items-center justify-content-center">
			<div class="col-10 m-0 p-0 mt-3">
				<div class="jumbotron shadow bg-custom animate__animated animate__bounceIn" id="landing-jumbo">
                    <h1>Contact</h1>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Landing Section -->

<!-- Contact Section -->
<div class="site-section bg-light animate__animated animate__fadeIn" id="site-section">
	<div class="container p-0">
		<div class="row text-center align-items-center justify-content-center">
			<div class="col-md-8 m-0 p-0">
                <h3 class="mb-3 animate__animated animate__fadeIn">Let's talk about what we can build together.</h3>
                <div class="container">
                    <!-- Messages -->
                <div>
                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        {% endfor %}
                    {% endif %}
                </div>
                <!-- Messages -->
                <!-- Contact Form -->
                <form method="POST">
                    {% csrf_token %}
                    <div class="form-group animate__animated animate__bounceInLeft">
                        {{ form.name }}
                    </div>
                    <div class="form-group animate__animated animate__bounceInRight">
                        {{ form.email }}
                    </div>
                    <div class="form-group animate__animated animate__bounceInLeft">
                        {{ form.phone }}
                    </div>
                    <div class="form-group animate__animated animate__bounceInRight">
                        {{ form.subject }}
                    </div>
                    <div class="form-group animate__animated animate__bounceInLeft">
                        {{ form.message }}
                    </div>
                    <div class="form-group animate__animated animate__rollIn">
                        <button type="submit" class="btn btn-lg bg-white btn-outline-dark border-0 shadow-sm" id="contact-form-submit"><i class="far fa-paper-plane"></i> Send</button>
                    </div>
                </form>
                <!-- Contact Form -->
                </div>
                
			</div>
		</div>
	</div>
</div>
<!-- Contact Section -->
{% endblock %}


{% block extra_scripts %}
<script>
    var contact_form_submit = $('#contact-form-submit');
    contact_form_submit.bind('mouseenter', () => {
        contact_form_submit.toggleClass('text-secondary underline_it');
    });
    contact_form_submit.bind('mouseleave', () => {
        contact_form_submit.toggleClass('text-secondary underline_it');
    });
</script>
{% endblock extra_scripts %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% load cloudinary %}
{%  block content %}
{% include "components/navbar.html" with active="/"  %}

<!-- Landing Section -->
<div class="site-section shadow bg-light animate__animated animate__fadeIn" id="home_landing_section">
	<div class="container p-0">
		<div class="row mt-2 text-center align-items-center justify-content-center">
			<div class="col-10 m-0 p-0 mt-5">
				<div class="jumbotron bg-custom mt-4 shadow animate__animated animate__animated animate__fadeInDown">
                    <h1 class="p-0 m-0"><strong>J. Harris</strong></h1>
                    <h1 class="p-0 m-0"><strong>Web Development</strong></h1>
                    <hr>
                    <h5 class="mt-2">E-commerce Shops / Artist Profiles / Small Business Sites</h5>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Landing Section -->
<div class="container-fluid demo align-items-center justify-content-center animate__animated animate__fadeIn" id="landing_contact_section">
    <div class="row">
        <!--Section: Content-->
        <section class="col text-center d-md-block align-items-center justify-content-center p-5 bg-white" id="landing_contact_section">
            <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="card shadow border-0">
                            <div class="card-body">
                                <h3>Creative Sites For Creative Brands</h3>
                                <a href="{% url 'core:projects' %}" class="btn btn-lg bg-light btn-outline-dark border-0 shadow-sm ">See My Work</a>
                            </div>                            
                        </div>                     
                    </div>
                    <div class="carousel-item">
                        <div class="card shadow border-0">
                            <div class="card-body">
                                <h3>Design, Front-End, Back-End</h3>
                                <a href="{% url 'core:about' %}" class="btn btn-lg bg-light btn-outline-dark border-0 shadow-sm ">What I'm About</a>
                            </div>                            
                        </div> 
                    </div>
                    <div class="carousel-item">
                        <div class="card border-0">
                            <div class="card-body">
                                <h3>Let's talk about how I can help you</h3>
                                <a href="{% url 'core:social' %}" class="btn mx-2 bg-light btn-outline-dark border-0 shadow-sm ">Social Media</a>
                                <a href="{% url 'core:contact' %}" class="btn mx-2 bg-light btn-outline-dark border-0 shadow-sm ">Contact</a>
                            </div>                            
                        </div> 
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </section>
        <!--Section: Content-->
    </div>
</div>

{% endblock content %}

{% block extra_scripts %}
<script>


</script>
{% endblock extra_scripts %}

templates/projects.html
{% extends "base.html" %}
{% load static %}
{% load cloudinary %}
{%  block content %}
{% include "components/navbar.html" with active="/projects"  %}


<!-- Landing Section -->
<div class="site-section shadow-lg bg-light animate__animated animate__fadeIn text-center align-items-center justify-content-center" id="landing-section">
	<div class="container p-0">
		<div class="row mt-5 text-center align-items-center justify-content-center">
			<div class="col-10 m-0 p-0 mt-3">
				<div class="jumbotron shadow bg-custom animate__animated animate__zoomIn" id="landing-jumbo">
                    <h1>Projects</h1>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Landing Section -->

<!-- Projects List Section -->
<div class="site-section bg-light animate__animated animate__fadeIn" id="site-section">
	<div class="container p-0">
		<div class="row text-center align-items-center justify-content-center">
			<div class="col-md-8 m-0 p-0 animate__animated animate__zoomIn">
				<!-- Content -->
				<div class="container my-5">
					<!-- Section: Block Content -->
					<section class="dark-grey-text text-center">
					  	<p class="text-muted w-responsive mx-auto mb-5"></p>
				  		<!-- Grid row -->
					  	<div class="row">
							<!-- Grid column -->
							{% for project in object_list %}
							<div class="col-lg-4 col-md-12 mb-4 shadow-sm rounded p-3 bg-white animate__animated animate__zoomIn">
				  				<div class="view overlay rounded z-depth-1">
									{% cloudinary project.image.public_id class="img-fluid" %}
									<a>
							  			<div class="mask rgba-white-slight"></div>
									</a>
						  		</div>
				  				<div class="px-3 pt-3 mx-1 mt-1 pb-0">
									<h4 class="font-weight-bold mt-1 mb-3">{{ project.title }}</h4>
									<p class="text-muted">{{ project.techs }}</p>
									<div class="btn-group">
										<a class="btn btn-sm bg-light btn-outline-dark border-0 shadow-sm m-1" href="{{ project.github }}" target="_blank"><i class="fab fa-github left"></i> View GitHub</a>
										<a class="btn btn-sm bg-light btn-outline-dark border-0 shadow-sm m-1" href="{{ project.url }}" target="_blank"><i class="fas fa-clone left"></i> View Live</a>
									</div>									
						  		</div>
							</div>
							 {% endfor %}
							<!-- Grid column -->
						</div>
						<!-- Bottom Pagination -->
						<div class="pagination mt-5 pt-2 mb-3 text-dark text-center align-items-center justify-content-center">
							<span class="step-links">
								{% if page_obj.has_previous %}
									<a href="?page=1">&laquo; FIRST</a>
									<a href="?page={{ page_obj.previous_page_number }}">PREVIOUS</a>
								{% endif %}
						
								<span class="current">
									Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
								</span>
						
								{% if page_obj.has_next %}
									<a href="?page={{ page_obj.next_page_number }}">NEXT</a>
									<a href="?page={{ page_obj.paginator.num_pages }}">LAST &raquo;</a>
								{% endif %}
							</span>
						</div>
						<!-- Bottom Pagination -->
					  	<!-- Grid row -->
				  	</section>
					<!-- Section: Block Content -->
				</div>
				<!-- Content -->
			</div>
		</div>
	</div>
</div>
<!-- Projects List Section -->


{% endblock %}